## **0. Import Libraries**

In [1]:
import os
import sys
sys.path.append(os.path.abspath('..'))

In [2]:
import pandas as pd
import numpy as np
from src import prophet_features

## **1. Feature Selection**

In [3]:
df = pd.read_parquet('../data/merged/m5_merged.parquet')
df.head()

,id,item_id,dept_id,cat_id,store_id,state_id,d,sales,date,wm_yr_wk,...,month,year,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI,sell_price
0,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,...,1,2011,No_Event,No_Event,No_Event,No_Event,0,0,0,9.58
1,HOBBIES_1_002_CA_1_validation,HOBBIES_1_002,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,...,1,2011,No_Event,No_Event,No_Event,No_Event,0,0,0,3.97
2,HOBBIES_1_003_CA_1_validation,HOBBIES_1_003,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,...,1,2011,No_Event,No_Event,No_Event,No_Event,0,0,0,2.97
3,HOBBIES_1_004_CA_1_validation,HOBBIES_1_004,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,...,1,2011,No_Event,No_Event,No_Event,No_Event,0,0,0,4.34
4,HOBBIES_1_005_CA_1_validation,HOBBIES_1_005,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,...,1,2011,No_Event,No_Event,No_Event,No_Event,0,0,0,2.98

In [4]:
df = df.set_index('id')
df.head()

,item_id,dept_id,cat_id,store_id,state_id,d,sales,date,wm_yr_wk,weekday,...,month,year,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI,sell_price
id,,,,,,,,,,,,,,,,,,,,,
HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,Saturday,...,1,2011,No_Event,No_Event,No_Event,No_Event,0,0,0,9.58
HOBBIES_1_002_CA_1_validation,HOBBIES_1_002,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,Saturday,...,1,2011,No_Event,No_Event,No_Event,No_Event,0,0,0,3.97
HOBBIES_1_003_CA_1_validation,HOBBIES_1_003,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,Saturday,...,1,2011,No_Event,No_Event,No_Event,No_Event,0,0,0,2.97
HOBBIES_1_004_CA_1_validation,HOBBIES_1_004,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,Saturday,...,1,2011,No_Event,No_Event,No_Event,No_Event,0,0,0,4.34
HOBBIES_1_005_CA_1_validation,HOBBIES_1_005,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,Saturday,...,1,2011,No_Event,No_Event,No_Event,No_Event,0,0,0,2.98

In [5]:
df['event_name_2'].value_counts()

event_name_2
No_Event          58205410
Easter               30490
Cinco De Mayo        30490
OrthodoxEaster       30490
Father's day         30490
Name: count, dtype: int64

In [6]:
df = prophet_features.combine_snap_features(df)
df = prophet_features.select_features(df)

In [7]:
df.head(10)

,item_id,store_id,sales,date,event_name_1,event_type_1,event_name_2,event_type_2,sell_price,snap
id,,,,,,,,,,
HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,CA_1,0,2011-01-29,No_Event,No_Event,No_Event,No_Event,9.58,0
HOBBIES_1_002_CA_1_validation,HOBBIES_1_002,CA_1,0,2011-01-29,No_Event,No_Event,No_Event,No_Event,3.97,0
HOBBIES_1_003_CA_1_validation,HOBBIES_1_003,CA_1,0,2011-01-29,No_Event,No_Event,No_Event,No_Event,2.97,0
HOBBIES_1_004_CA_1_validation,HOBBIES_1_004,CA_1,0,2011-01-29,No_Event,No_Event,No_Event,No_Event,4.34,0
HOBBIES_1_005_CA_1_validation,HOBBIES_1_005,CA_1,0,2011-01-29,No_Event,No_Event,No_Event,No_Event,2.98,0
HOBBIES_1_006_CA_1_validation,HOBBIES_1_006,CA_1,0,2011-01-29,No_Event,No_Event,No_Event,No_Event,1.00,0
HOBBIES_1_007_CA_1_validation,HOBBIES_1_007,CA_1,0,2011-01-29,No_Event,No_Event,No_Event,No_Event,7.94,0
HOBBIES_1_008_CA_1_validation,HOBBIES_1_008,CA_1,12,2011-01-29,No_Event,No_Event,No_Event,No_Event,0.46,0
HOBBIES_1_009_CA_1_validation,HOBBIES_1_009,CA_1,2,2011-01-29,No_Event,No_Event,No_Event,No_Event,1.56,0
HOBBIES_1_010_CA_1_validation,HOBBIES_1_010,CA_1,0,2011-01-29,No_Event,No_Event,No_Event,No_Event,3.17,0

In [10]:
df.info()

<class 'pandas.DataFrame'>
Index: 58327370 entries, HOBBIES_1_001_CA_1_validation to FOODS_3_827_WI_3_validation
Data columns (total 10 columns):
 #   Column        Dtype
---  ------        -----
 0   item_id       str
 1   store_id      str
 2   sales         int64
 3   date          datetime64[us]
 4   event_name_1  str
 5   event_type_1  str
 6   event_name_2  str
 7   event_type_2  str
 8   sell_price    float64
 9   snap          int64
dtypes: datetime64[us](1), float64(1), int64(2), str(6)
memory usage: 9.0 GB

## **2. Feature Extraction**